PROJECT_NAME ?= <example-project>
DEV_HOST ?= $(PROJECT_NAME).dev
PRODUCTION_HOST ?= $(PROJECT_NAME).com
LOCAL_HOST ?= localhost:3000
STAGING_HOST ?= $(PROJECT_NAME).web.staging.minasithil.genero.fi

PRODUCTION_REMOTE_HOST ?= deploy@$(PRODUCTION_HOST):/home/www/$(PROJECT_NAME)
STAGING_REMOTE_HOST ?= deploy@minasithil.genero.fi:/var/www/staging/$(PROJECT_NAME)
